# 七、异常



## 7.1 异常概述与异常体系结构

- 在使用计算机语言进行项目开发的过程中，即使程序员把代码写得尽善尽美，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如：客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅等等。



***异常：***

- 在Java 语言中，将***<u>程序执行中发生的不正常情况</u>***称为“异常”。( 开发过程中的**语法错误和逻辑错误<u>不是异常</u>**）



***异常事件分为两类：***

- `Error`：***Java 虚拟机无法解决的<u>严重问题</u>***。如：`JVM` 系统内部错误、资源耗尽等严重情况。比如：`StackOverflowError` 和`OOM`。**一般不编写针对性的代码进行处理。**

  - Java 虚拟机无法解决的严重问题。如：`JVM` 系统内部错误、资源耗尽等严重情况。比如：`StackOverflowError` 和`OOM`。一般不编写针对性的代码进行处理。

  ```java
  public class ErrorTest {
      public static void main(String[] args) {
          //1. 栈溢出：java.lang.StackOverflowError
          // main(args);
          //2. 堆溢出：java.lang.OutOfMemoryError
          // Integer[] arr = new Integer[1024*1024*1024];
      }
  }
  ```

  

- `Exception`：其它因编程错误或偶然的外在因素导致的一般性问题，***可以使用<u>针对性的代码</u>进行处理***。例如：

  - 空指针访问；
  - 试图读取不存在的文件；
  - 网络连接中断；
  - 数组角标越界；



***两种解决方法：***

- **一是**遇到错误就终止程序的运行。
- **另一种**方法是由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。
- ***捕获错误最理想的是在编译期间，但有的错误只有在运行时才会发生***。比如：除数为0，数组下标越界等



***异常分类：编译时异常和运行时异常：***

- 运行时异常：
  - 是指***编译器不要求强制处置的异常***。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。`java.lang.RuntimeException` 类及它的子类都是运行时异常。
  - 对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。
- 编译时异常：
  - 是指***编译器要求必须处置***的异常。即程序在运行时由于外界因素造成的一般性异常。编译器要求Java 程序必须捕获或声明所有编译时异常。
  - 对于这类异常，如果程序不处理，可能会带来意想不到的结果。



## 7.2 常见异常

```python
java.lang.Throwable
	|----java.lang.Error: 一般不编写针对性的代码进行处理
	|----java.lang.Exception: 可以进行异常处理
		|---- 编译时异常(checked)
			|----IOEXception
				|----FileNotFoundException
    		|----ClassNotFoundException
		|---- 运行时异常(unchecked, runtimeException)
			|----NullPointerException
			|----ArrayIndexOutOfBoundsException
			|----ClassCaseException
			|----NumberFormatException
			|----InputMismatchException
			|----ArithmaticException
```



***举例：***

```java
public class ExceptionTest {
    // ****************** 以下是编译时异常***************************
    @Test
    public void test7() {
        // File file = new File("hello.txt");
        // FileInputStream fis = new FileInputStream(file);
        //
        // int data = fis.read();
        // while(data != -1){
        // System.out.print((char)data);
        // data = fis.read();
        // }
        //
        // fis.close();
    }

    // ****************** 以下是运行时异常***************************
    // ArithmeticException
    @Test
    public void test6() {
        int a = 10;
        int b = 0;
        System.out.println(a / b);
    }

    // InputMismatchException
    @Test
    public void test5() {
        Scanner scanner = new Scanner(System.in);
        int score = scanner.nextInt();
        System.out.println(score);
        scanner.close();
    }

    // NumberFormatException
    @Test
    public void test4() {
        String str = "123";
        str = "abc";
        int num = Integer.parseInt(str);
    }

    // ClassCaseException
    @Test
    public void test3() {
        Object obj = new Date();
        String str = (String) obj;
    }

    // ArrayIndexOutOfBoundsException
    @Test
    public void test2() {
        // int[] arr = new int[10];
        // System.out.println(arr[10]);
        // String str = "abc";
        // System.out.println(str.charAt(3));
    }

    // NullPointerException
    @Test
    public void test1() {
        // int[] arr = null;
        // System.out.println(arr[3]);
        // String str = "abc";
        // str = null;
        // System.out.println(str.charAt(0));
    }
}
```



## 7.3 异常处理机制一：try-catch-finally

- 在编写程序时，经常要在可能出现错误的地方加上检测的代码，如进行 x/y 运算时，要检测分母为0，数据为空，输入的不是数据而是字符等。过多的`if-else` 分支会导致程序的***代码加长、臃肿，可读性差***。因此采用异常处理机制；
- Java 采用的异常处理机制，是将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护；



***异常处理机制一：try-catch-finally：***

- `try`：

  捕获异常的第一步是用`try{⋯}` 语句块选定捕获异常的范围，将可能出现异常的代码放在try 语句块中。

- `catch(Exceptiontypee)`：

  - 在`catch` 语句块中是对异常对象进行处理的代码。***每个`try` 语句块可以伴随<u>一个或多个</u>catch 语句***，用于处理可能产生的不同类型的异常对象。
  - 捕获异常的有关信息：与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。
  - `getMessage()` 获取异常信息，返回字符串。
  - `printStackTrace()` 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值`void`。

- `finally`：

  - 捕获异常的最后一步是通过finally 语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理。
  - 不论在`try` 代码块中是否发生了异常事件，`catch` 语句是否执行，`catch`语句是否有异常，***<u>`try`或`catch` 语句中是否有`return`</u>***，`finally` 块中的语句***<u>都会被执行</u>***。
  - finally 语句和catch 语句是任选的。

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionTest1 {
    @Test
    public void test2() {
        try {
            File file = new File("hello.txt");
            FileInputStream fis = new FileInputStream(file);
            int data = fis.read();
            while (data != -1) {
                System.out.print((char) data);
                data = fis.read();
            }
            fis.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void test1() {
        String str = "123";
        str = "abc";
        try {
            int num = Integer.parseInt(str);
            System.out.println("hello-----1");
        } catch (NumberFormatException e) {
            // System.out.println(" 出现数值转换异常了，不要着急....");
            //String getMessage():
            // System.out.println(e.getMessage());
            //printStackTrace():
            e.printStackTrace();
        } catch (NullPointerException e) {
            System.out.println(" 出现空指针异常了，不要着急....");
        } catch (Exception e) {
            System.out.println(" 出现异常了，不要着急....");
        }
        // System.out.println(num);
        System.out.println("hello----2");
    }
}
```



***`finally`的使用：***

1. `finally` 是可选的。
2. `finally` 中声明的是一定会被执行的代码。即使`catch` 中又出现异常了，`try`中有`return` 语句，`catch` 中有`return` 语句等情况。

3. 像数据库连接、输入输出流、网络编程`Socket` 等资源，`JVM` 是不能自动的回收的，我们***<u>需要自己手动的进行资源的释放</u>***。此时的资源释放，就需要声明在`finally` 中。

```java
import org.testng.annotations.Test;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class FinallyTest {
    @Test
    public void test2() {
        FileInputStream fis = null;
        try {
            File file = new File("hello1.txt");
// 文件可能不存在，而出现异常
            fis = new FileInputStream(file);
            int data = fis.read();
            while (data != -1) {
                System.out.print((char) data);
                data = fis.read();
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (fis != null)
                    fis.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    @Test
    public void testMethod() {
        int num = method();
        System.out.println(num);
    }

    public int method() {
        try {
            int[] arr = new int[10];
            System.out.println(arr[10]);
            return 1;
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
            return 2;
        } finally {
            System.out.println(" 我一定会被执行");
            return 3;
        }
    }

    @Test
    public void test1() {
        try {
            int a = 10;
            int b = 0;
            System.out.println(a / b);
        } catch (ArithmeticException e) {
// e.printStackTrace();
            int[] arr = new int[10];
            System.out.println(arr[10]);
        } catch (Exception e) {
            e.printStackTrace();
        }
// System.out.println(" 我好慢呀~~~");
        finally {
            System.out.println(" 我好慢呀~~~");
        }
    }
}
```



## 7.4 异常处理机制二：throws

如果一个方法( 中的语句执行时) 可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。

在方法声明中用throws 语句可以声明抛出异常的列表，`throws` 后面的异常类型***可以是方法中产生的异常类型，也可以是它的<u>父类</u>***。

1. `throws + 异常类型`"写在***<u>方法的声明处</u>***。指明此方法执行时，可能会抛出的异常类型。
   - 一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足`throws` 后异常类型时，就会被抛出。***异常代码后续的代码，就<u>不再执行</u>！***
   - 关于异常对象的产生： ① 系统**自动生成**的异常对象；② **手动生成**一个异常对象，并抛出(`throw`)
2. 体会：`try-catch-finally`：真正的将异常给处理掉了。`throws` 的方式只是将异常抛给了方法的调用者。并没有真正将异常处理掉。
3. 开发中如何选择使用try-catch-finally 还是使用throws ？
   - 如果父类中被重写的方法没有throws 方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally 方式处理。
   - 执行的方法a 中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws 的方式进行处理。而执行的方法a 可以考虑使用try-catch-finally 方式进行处理。

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionTest2 {
    public static void main(String[] args) {
        try {
            method2();
        } catch (IOException e) {
            e.printStackTrace();
        }
        method3();
    }

    public static void method3() {
        try {
            method2();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("error.");
        }
    }

    public static void method2() throws IOException {
        method1();
    }

    public static void method1() throws FileNotFoundException, IOException {
        File file = new File("hello1.txt");
        FileInputStream fis = new FileInputStream(file);
        int data = fis.read();
        while (data != -1) {
            System.out.print((char) data);
            data = fis.read();
        }
        fis.close();
        System.out.println("hahaha!");
    }
}
```



***重写方法声明抛出异常：***

- ***子类重写的方法抛出的异常类型==<u>不大于</u>==父类被重写的方法抛出***的异常类型

```java
import java.io.FileNotFoundException;
import java.io.IOException;

public class OverrideTest {
    public static void main(String[] args) {
        OverrideTest test = new OverrideTest();
        test.display(new SubClass());
    }
    public void display(SuperClass s){
        try {
            s.method();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
class SuperClass{
    public void method() throws IOException{
    }
}
class SubClass extends SuperClass{
    public void method()throws FileNotFoundException {
    }
}
```



## 7.5 手动抛出异常

Java 异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，也可根据需要***使用人工创建并抛出***。

首先要生成异常类对象，然后通过throw 语句实现抛出操作( 提交给Java 运行环境)。

可以抛出的异常必须是`Throwable` 或其子类的实例。下面的语句在编译时将会产生语法错误：

```java
public class StudentTest {
    public static void main(String[] args) {
        try {
            Student s = new Student();
            // s.regist(1001);
            s.regist(-1001);
            System.out.println(s);
        } catch (Exception e) {
            // e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }
}
class Student{
    private int id;
    public void regist(int id) throws Exception{
        if(id > 0){
            this.id = id;
        }else{
            // System.out.println(" 您输入的数据非法！ ");
            // 手动抛出异常
            // throw new RuntimeException(" 您输入的数据非法！ ");
            throw new Exception(" 您输入的数据非法！ ");
        }
    }
    @Override
    public String toString() {
        return "Student [id=" + id + "]";
    }
}
```



## 7.6 用户自定义异常类

一般地，用户自定义异常类都是`RuntimeException`的子类。

- 自定义异常类通常***需要编写几个重载的<u>构造器</u>***。
- 自定义异常需要提供`serialVersionUID`。
- 自定义的异常通过`throw` 抛出。
- 自定义异常最重要的是异常类的名字，当异常出现时，可以***根据名字判断异常***类型。

```java
public class MyException extends RuntimeException {
    static final long serialVersionUID = -7034897193246939L;

    public MyException() {
    }

    public MyException(String msg) {
        super(msg);
    }
}
```



## 7.7 异常总结

![异常总结](image/异常总结.png)

